### PR TITLE
Bug873088 - Add codec libraries to extract-files.sh

### PR DESCRIPTION
**Pull request by sotaroikeda**
https://bugzilla.mozilla.org/show_bug.cgi?id=873088

### CODE REVIEW

**Comment by andreasgal** [comment]
The tabs look funky. Can you double check that and then merge? r=me

**Comment by sotaroikeda** [comment]
Oh, I did not recognized tabs are used around the change.

**Comment by sotaroikeda** [comment]
fixed spaces and tabs problem

**Comment by michaelwu** [comment]
Thanks!

You might want to do an interactive rebase to clean up the commits next time, but it's no big deal here.

**Comment by sotaroikeda** [comment]
Thanks,

> You might want to do an interactive rebase to clean up the commits next time, but it's no big deal here.

Yes, thanks for the advice!

**Pull request merged**
